name: Deploy with Helmfile
description: Deploy applications using Helmfile with secret management

inputs:
  helmfile-diff-args:
    description: 'Arguments to pass to helmfile diff, default to helmfile-args'
    required: false
  helmfile-args:
    description: 'Arguments to pass to helmfile'
    required: true
  kube-config:
    description: 'Base64 encoded kubeconfig'
    required: true
  chatty-env:
    description: 'Chatty environment variables'
    required: false

runs:
  using: composite
  steps:
    - name: Helmfile init
      uses: XyLearningProgramming/helm.x3huang.dev/.github/actions/helmfile-init@main

    - name: Set up kubeconfig
      shell: bash
      run: |
        mkdir -p $HOME/.kube
        echo '${{ inputs.kube-config }}' | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Upsert Kubernetes secret
      if: inputs.chatty-env != ''
      shell: bash
      run: |
        # Write env content to temporary file
        echo "${{ inputs.chatty-env }}" > /tmp/chatty.env

        # Use apply script to create/update secrets
        ./deploy/secret/apply.sh /tmp/chatty.env

        # Clean up temp file
        rm -f /tmp/chatty.env

    - name: Dry-run (Diff) before Apply
      uses: helmfile/helmfile-action@v2.0.4
      with:
        helmfile-args: diff ${{ inputs.helmfile-diff-args || inputs.helmfile-args }} --detailed-exitcode
      continue-on-error: true

    - name: Apply Changes
      uses: helmfile/helmfile-action@v2.0.4
      with:
        helmfile-args: apply ${{ inputs.helmfile-args }}
